from . import account
from . import account_move_reversal
from . import ln10_co_etet
from . import res_city
from . import res_company
from . import res_country
from . import res_currency
from . import res_lang
from . import res_partner
from . import tax_mapping_modification
from . import uom_uom
